### ISSUE TITLE
mac下能正常初始化，没有报错，一直捕获中

### ISSUE THREAD

**Issue by baifengbai** [lecepin/WeChatVideoDownloader#1]
对微信有特殊版本要求吗

**Comment by baifengbai** [comment]
对微信有特殊版本要求吗

**Comment by lecepin** [comment]
可能以下情况导致的：
- 360 等杀毒软件禁用了软件的某些功能
- 系统中存在其他优先级更高的代理软件，导致没有命中

你可以按照这两个方向重试一下

**Comment by baifengbai** [comment]
好的谢谢，把其他代理都关了还是不行

**Comment by lecepin** [comment]
> 好的谢谢，把其他代理都关了还是不行

估计顺序问题。

本软件没做代理破坏性操作，所以如果有优先级更高的代理配置，会被忽略掉。

建议：

1. 先把所有代理软件关闭，尤其是 pac 系列的。
2. 然后打开本软件
