### ISSUE TITLE
v2.1.2的微信视频地址无效

### ISSUE THREAD

**Issue by zikonde** [lecepin/WeChatVideoDownloader#124]
你好，这是一个很不错的程序我也很佩服你能够做出来这么好的app的能力和创意。除此之外，我我使用它的时候遇见一些希望系可以修复的问题。

1、新的版本还存在一些获取到的视频地址无效的情况（像微信小视频和b站），下载到电脑也是看不了。

![IMG_20240114_140856.jpg](https://github.com/lecepin/WeChatVideoDownloader/assets/103549398/032765d4-97e9-46e6-907a-e8e4cc1fdf3e)

![IMG_20240114_141000.jpg](https://github.com/lecepin/WeChatVideoDownloader/assets/103549398/7029edff-f06a-43d3-aa99-8255ca93caf5)

2、然后我发现它获取腾讯视频地址时，只能获取到第一播放的广告，能预览，也能下载和打开。这个倒是没问题，问题只是获取不了后面播放的视频。

https://github.com/lecepin/WeChatVideoDownloader/assets/103549398/020ec88d-dbb8-4653-bbc9-7582ab020347

3、没每一个视频地址只能被识别一次，不管清空了前面捕获的记录，也不管用户是否下载成功了。

感谢你的辛勤工作，希望你能帮助解决这些问题🦾

**Comment by lecepin** [comment]
这是v1.x的版本，已经不维护了，可以使用v2.x的版本
