### ISSUE TITLE
下载的视频播放不了，不知道为啥？也无法预览。

### ISSUE THREAD

**Issue by hlcc** [lecepin/WeChatVideoDownloader#18]

**Comment by PengJiang520** [comment]
一样，我看了是微信更新了版本

**Comment by PengJiang520** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/14941858/195311059-e4da9c49-2fe1-41ea-b13d-4b36726e7ab0.png">

**Comment by PengJiang520** [comment]
我回退到微信3.4.0版本也是如此

**Comment by PengJiang520** [comment]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/14941858/195313774-bfe7481b-63bd-42a1-bca3-20c7ed609fb9.png">

**Comment by GGxinxian** [comment]
> 我回退到微信3.4.0版本也是如此

我的也是这个样子，视频播放不了，问下你那边解决了吗？

**Comment by hlcc** [comment]
先将视频转发到朋友或文件助手，然后从文件助手打开链接，这样就能识别到下载的文件了。文件大小是2B，但也不能预览。下载后就可以正常播放了。

**Comment by GGxinxian** [comment]
> 先将视频转发到朋友或文件助手，然后从文件助手打开链接，这样就能识别到下载的文件了。文件大小是2B，但也不能预览。下载后就可以正常播放了。

我使用了你的方法，但是我的视频还是无法打开。
![image](https://user-images.githubusercontent.com/108313246/197102556-be3ede6c-6845-4ce2-898a-0613329a4e72.png)

**Comment by hlcc** [comment]
<img width="912" alt="截屏2022-10-21 11 15 15" src="https://user-images.githubusercontent.com/14193599/197103434-38d8856a-bb4c-4a5c-9006-e5a4b59da72b.png">

步聚很重要
1. 转发到联系人或文件助手
2. 打开下载软件
3. 从联系人或文件助手打开视频链接
4. 如果没有识别到，刷新一下视频页面，或重新打开软件。

![Uploading 截屏2022-10-21 11.18.50.png…]()
注：按这种方法识别到的下载链接一般只有1个，然后文件大小一般是几K或几B这样的，预览可以听到声音，但没有画面。建议你关掉其它视频页面再试试。

**Comment by GGxinxian** [comment]
好的，非常感谢您提供的方法，但是在我这里他还是无法播放，可能是系统不同的原因吧

**Comment by sunwen0402** [comment]
把没有画面的视频导入剪映里面就有了, 然后剪映里面重新导出视频, 估计和视频编码有关, 有的播放器有画面,有的播放器无画面

**Comment by lweo** [comment]
> 

应该不是codec的问题。我换万能播放器还是打不开

**Comment by lap888** [comment]
看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊
[直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)
