### ISSUE TITLE
老大有没有 yotube的？

### ISSUE THREAD

**Issue by lap888** [lecepin/WeChatVideoDownloader#22]
老大有没有 yotube的？

**Comment by lap888** [comment]
> 老大有没有 yotube的？

youtube

**Comment by cubale** [comment]
> > 老大有没有 yotube的？
> 
> youtube

youtube的下载很容易，很多软件甚至网页插件都能下载，最有名的是IDM下载器。难下载的反而是微信视频号

**Comment by lecepin** [comment]
可以用这个在线工具    https://zh.savefrom.net/226/
