### ISSUE TITLE
大神！视频号下载下来的视频目前无法打开了😭😭😭

### ISSUE THREAD

**Issue by vvkkfwq** [lecepin/WeChatVideoDownloader#25]
视频下载完成之后mac会无法打开，显示解析失败

**Comment by miracle859** [comment]
WIN 版本也是 下载以后无法打开

**Comment by vvkkfwq** [comment]
> WIN 版本也是 下载以后无法打开

大哥，想请教下还有别的方法能够下载视频号的视频吗？

**Comment by chenjiaqi001** [comment]
同，目前感觉是因为视频号把视频切割开了，导致每一段都无法独立播放

**Comment by foxfire881** [comment]
好像是视频加密了，下载回来不是MP4格式。

**Comment by Gmuzi** [comment]
一样，无法播放，只能下载，大佬还更新吗

**Comment by Gmuzi** [comment]
只能走录屏的老路了，大佬速速更一波哇

**Comment by clarity09** [comment]
大神 快来更新一波

**Comment by Stainless5792** [comment]
召唤大神！！！

**Comment by china5188** [comment]
大佬，来一波更新吧，把这个加密给破解了。。。否则都是“能下载，不能播放的 ”

**Comment by lap888** [comment]
看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊
[直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)

**Comment by lap888** [comment]
> 看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊 [直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)

http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQBuPPjGAhn5XULO9MXv3LkD4ONUsqVqjicnxQgXXsV7nCPVWvaicnUYX3Rpiaxky7FuI1xGPRicSIj6v54DFXzV8Dup&token=Cvvj5Ix3eez1HP7JibvohWUM3xWundFzwB9CicAUwwhY4sWm7S4XzreTDibdr4iavafxlV7UGxLDSGp2UibOpXXngoW4jvrciaoicVhdicgBrVEvvsbxQrdpPLvXjWc4ZjTk8haic&idx=1&bizid=1023&dotrans=0&hy=SH&m=
