### ISSUE TITLE
微信会隐藏原来的地址，生成一个新的加密的地址，加密的文件一般比未加密的大了50MB

### ISSUE THREAD

**Issue by qq148376839** [lecepin/WeChatVideoDownloader#28]
加密链接：

**Comment by qq148376839** [comment]
> 

https://finder.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFhC1yAuUAWqZ6wBRib1viaghfELGORF4myL81gae7npc0Xib1zib0nNvzj7ickpiaJWiaicfC5VBLzLe3KTapYxxFIhuOMFWsbxQ7CAE7viaSticKJsmiaQ&adaptivelytrans=0&bizid=1023&dotrans=2991&hy=SH&idx=1&ilogo=1&m=2fa78aba7747c0326a0d1b6a3ec694c3&scene=103&t=1&web=1&token=cztXnd9GyrElIavIvyVHQkqHG2FA38KvyRz95bBia2duhEQUyMtSkB93p6Hpm2ARO2oYf4zhBLIIico7Qh4TFRStF9c7M1XiceemrBuKnHCKEureKXFWiaoNTib6LHicr3tGTy&fexam=1&X-snsvideoflag=xW29	
未加密链接：
https://finder.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFhC1yAuUAWqZ6wBRib1viaghfELGORF4myL81gae7npc0Xib1zib0nNvzj7ickpiaJWiaicfC5VBLzLe3KTapYxxFIhuOMFWsbxQ7CAE7viaSticKJsmiaQ&token=x5Y29zUxcibDBmIKFI2cAQeudng6ibEdv8nb00ENPvEknvRZ8wSqzz2850myju77mXU3DUXuWrJNc&idx=1&adaptivelytrans=0&bizid=1023&dotrans=2991&hy=SH&ilogo=1&m=2fa78aba7747c0326a0d1b6a3ec694c3&scene=103&t=1&finderextscene=6&fexam=1&web=1&X-snsvideoflag=xW29&taskid=0

**Comment by YangThinking** [comment]
主要是Token的字符串发生变化，截包的字符串与解密的字符串长度不一样，解密后的变短，如何解密token字符串？能否给一些指导，谢谢！

**Comment by qq148376839** [comment]
> 

暂时没爬到具体什么逻辑做的隐藏，不过可以通过卡代理的方式去获取到真实的地址，有点麻烦，也不是100%成功。

**Comment by china5188** [comment]
> > 
> 
> 暂时没爬到具体什么逻辑做的隐藏，不过可以通过卡代理的方式去获取到真实的地址，有点麻烦，也不是100%成功。

你好，可否分享一下 怎么卡代理呢？   不怕麻烦。。哈哈
