### ISSUE TITLE
1月视频号流媒体加密以后，下载正常下载，但不能观看了，那么那些付费的机器人小程序是怎么得到未加密的地址的？

### ISSUE THREAD

**Issue by china5188** [lecepin/WeChatVideoDownloader#29]
1月视频号流媒体加密以后，下载正常下载，但不能观看了，那么那些付费的机器人小程序是怎么得到未加密的地址的？

**Comment by qiaowei361** [comment]
同样遇到这样的问题

**Comment by BiFang666** [comment]
> 1月视频号流媒体加密以后，下载正常下载，但不能观看了，那么那些付费的机器人小程序是怎么得到未加密的地址的？

你可以试试这样，先把要下载的视频发给机器人，然后打开软件，再打开机器人发给你的视频，这时候看看软件能不能抓包到机器人发给你的视频，能预览就代表成功了，我用这个方法下的视频都能看

**Comment by BiFang666** [comment]
> 同样遇到这样的问题
你可以试试这样，先把要下载的视频发给机器人，然后打开软件，再打开机器人发给你的视频，这时候看看软件能不能抓包到机器人发给你的视频，能预览就代表成功了，我用这个方法下的视频都能看

**Comment by wan-kenny** [comment]
确实加密了,然后只能下载不能播放了

**Comment by wan-kenny** [comment]
看看有什么解决方案没有把

**Comment by wan-kenny** [comment]
哪个机器人呢?

**Comment by 44886** [comment]
大家去看 @不坑老师 的公众号文章，介绍了如何用这个工具来下载视频号视频的，2023年3月13日，亲测有效！

**Comment by simplefeel** [comment]
3.28 按照公众号方式测试 无法正常播放

**Comment by euukey** [comment]
> 大家去看 @不坑老师 的公众号文章，介绍了如何用这个工具来下载视频号视频的，2023年3月13日，亲测有效！

2023.4.3fiddler亲测有效
