### ISSUE TITLE
Mac不行，20230413亲测

### ISSUE THREAD

**Issue by Endy-c** [lecepin/WeChatVideoDownloader#32]
无法获取视频地址，且安装pubkey到受信任根证书，则拥有privkey的人可以直接登录你的Mac，有点凶险

**Comment by woainiee520** [comment]
> 无法获取视频地址，且安装pubkey到受信任根证书，则拥有privkey的人可以直接登录你的Mac，有点凶险

这种情况下该怎么办，那个证书，可以删除么

**Comment by Endy-c** [comment]
“钥匙串访问.app”->系统->找到这个证书

**Comment by woainiee520** [comment]
> “钥匙串访问.app”->系统->找到这个证书

那个开头的，主要证书很多也不敢乱删，看不出来

**Comment by Endy-c** [comment]
1、系统这一栏下不会有很多证书，都是一些自签名证书，其中有两个是苹果自带的
2、如果没记错的话是有效期到2099年那个

**Comment by woainiee520** [comment]
> 1、系统这一栏下不会有很多证书，都是一些自签名证书，其中有两个是苹果自带的 2、如果没记错的话是有效期到2099年那个

<img width="724" alt="image" src="https://user-images.githubusercontent.com/32295902/233833296-b162815e-6266-445e-af34-a3c638b86377.png">
是不是这个

**Comment by Endy-c** [comment]
> > 1、系统这一栏下不会有很多证书，都是一些自签名证书，其中有两个是苹果自带的 2、如果没记错的话是有效期到2099年那个
> 
> <img alt="image" width="724" src="https://user-images.githubusercontent.com/32295902/233833296-b162815e-6266-445e-af34-a3c638b86377.png">
> 
> 是不是这个

对的

**Comment by woainiee520** [comment]
好的谢谢
