### ISSUE TITLE
mac可以下载，但下载下来的视频文件无法播放，换了几个播放器都不行

### ISSUE THREAD

**Issue by zhuqinghua** [lecepin/WeChatVideoDownloader#33]
mac可以下载，但下载下来的视频文件无法播放，换了几个播放器都不行
<img width="964" alt="image" src="https://user-images.githubusercontent.com/22886812/231695249-f1d9f5c5-19cf-4839-a215-10266658403a.png">

**Comment by sheephe** [comment]
https://github.com/lecepin/WeChatVideoDownloader/issues/30#issuecomment-1467478828

**Comment by otter666** [comment]
不能播放的就是不对，跟播放器无关。监听列表里会有好几个链接，你挨个点击预览，能播放那个才下载下来。

**Comment by lap888** [comment]
看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊
[直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)
