### ISSUE TITLE
Mac的安装完了打不开哦

### ISSUE THREAD

**Issue by davidqd** [lecepin/WeChatVideoDownloader#34]
无法打开“WeChatVideoDownloader”，因为无法验证开发者。
<img width="475" alt="image" src="https://user-images.githubusercontent.com/131733725/234162941-eb6d2241-8ea7-4608-80ea-7aff3578e041.png">

**Comment by lecepin** [comment]
参考：https://zhuanlan.zhihu.com/p/611748301
