### ISSUE TITLE
2023.5.24已经下载不了了，期待大神修复

### ISSUE THREAD

**Issue by wzj820222** [lecepin/WeChatVideoDownloader#36]

**Comment by JaneWater** [comment]
一样一样。就是传到手机助手，下载下来的一样打不开，预览不了。

**Comment by stevensia** [comment]
是的，可以下载，但是无法播放，可能文件加密了？

**Comment by ENDLESS-WIND** [comment]
微信视频号又更新了 加密了应该

**Comment by jingslunt** [comment]
https://finder.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQAEdCuIXNFicTWiajMicrXS3vqrs2YIxc0sUXricVvp8mC87FPdwrwKlywCZn5Uj5w4e8h2Zeyh4wF1yvXNbPJRF5Bq&bizid=1023&dotrans=0&hy=SH&idx=1&m=&web=1&token=6xykWLEnztK2zt83f0xTzfskHy5wKiaibjrzkImQ4ghN43LU8T4jOmW1BoP86hL2EhXGc9oROh5MXiaHzz2x2l2Pq0a6YLR3P9g3cqObvustQ0u9rgw6Id1Wzl2D80ibQJNP&fexam=1&X-snsvideoflag=xW20

**Comment by lap888** [comment]
看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊
[直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)
