### ISSUE TITLE
大神不更了么，太可惜了

### ISSUE THREAD

**Issue by mapleshadow** [lecepin/WeChatVideoDownloader#37]
RT，期待继续更新啊

**Comment by sunjchyt** [comment]
非常期待更新 现在下载不了了

**Comment by snowball00** [comment]
试了一下，可以用。不要从视频号进去，从电脑版微信侧边栏的“搜一搜”那里进去，然后输入你要下载的视频标题，点击搜索，出来的结果里再选“视频号”，软件里跳出的链接就可以预览了，下载完是可以播放的。

**Comment by arche77** [comment]
> 试了一下，可以用。不要从视频号进去，从电脑版微信侧边栏的“搜一搜”那里进去，然后输入你要下载的视频标题，点击搜索，出来的结果里再选“视频号”，软件里跳出的链接就可以预览了，下载完是可以播放的。

你好，你是用的win吗？我是mac，也是搜一搜，点视频号，打开。再去看软件窗口中，预览或者下载都是不能用的呀。就是网上有人说的文件大小对，200多M，但是加密的打不开呀。

**Comment by snowball00** [comment]
> > 试了一下，可以用。不要从视频号进去，从电脑版微信侧边栏的“搜一搜”那里进去，然后输入你要下载的视频标题，点击搜索，出来的结果里再选“视频号”，软件里跳出的链接就可以预览了，下载完是可以播放的。
> 
> 你好，你是用的win吗？我是mac，也是搜一搜，点视频号，打开。再去看软件窗口中，预览或者下载都是不能用的呀。就是网上有人说的文件大小对，200多M，但是加密的打不开呀。

我是win，能播放，mac的情况不太清楚。

**Comment by jianbujian** [comment]
> 试了下，可以用。不要从视频号进去，从电脑版微信旁边栏的“搜一搜”那里进去，然后输入你要下载的视频标题，点击搜索索，出来的结果里再选“视频号”，软件里跳出的链接就可以预览了，下载完成是可以播放的。

亲测，通过搜一搜预览的视频链接是可以抓取的，不过用fiddler这些抓包软件都可以直接抓取到

**Comment by csyhping** [comment]
2023-5-31
尝试了搜一搜 没有监听到

**Comment by sunjchyt** [comment]
可以了 。我重启电脑以后 按照说的   可以用了 
非常感谢

**Comment by sunjchyt** [comment]
通过搜一下搜可以下载，但是原视频被压缩了，下载下来不太清晰了

**Comment by sunjchyt** [comment]
收到 ，非常感谢



在 2023-06-08 17:23:56，"rTnrWE" ***@***.***> 写道：

通过搜一下搜可以下载，但是原视频被压缩了，下载下来不太清晰了

去掉&token=前面的一些参数就是清晰视频

**Comment by lap888** [comment]
看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊
[直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)

**Comment by lap888** [comment]
> 看这个视频，下载方式便捷，有需要的联系微信 wkc19891 白嫖勿扰啊 [直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)

可以下载高清原视频

**Comment by hpyer** [comment]
> > 试了一下，可以用。不要从视频号进去，从电脑版微信侧边栏的“搜一搜”那里进去，然后输入你要下载的视频标题，点击搜索，出来的结果里再选“视频号”，软件里跳出的链接就可以预览了，下载完是可以播放的。
> 
> 你好，你是用的win吗？我是mac，也是搜一搜，点视频号，打开。再去看软件窗口中，预览或者下载都是不能用的呀。就是网上有人说的文件大小对，200多M，但是加密的打不开呀。

不用打开视频详情页的，，就在搜索结果的列表页，视频会自动播放，这个时候抓取到的视频就是未加密的，视频地址是：https://findermp.video.qq.com 开头的
