### ISSUE TITLE
2023-6-7测试  视频号把视频已完全加密，下载下来也无法播放

### ISSUE THREAD

**Issue by harbin-walk** [lecepin/WeChatVideoDownloader#38]

**Comment by 666wwx** [comment]
同样的问题

**Comment by lap888** [comment]
你用的mac还是win？

**Comment by Jerryyuanyuan** [comment]
2023-06-09 亲测，win端，抓包下载的视频无法播放

**Comment by zeal-one** [comment]
+1 视频加密了 用MP4播放器打开失败

**Comment by lap888** [comment]
现在那个小程序犀牛，收费，还是可以下载的

**Comment by Jerryyuanyuan** [comment]
> +1 视频加密了 用MP4播放器打开失败

用pc浏览器，搜一搜，搜到对应视频后有不加密的视频，亲测有效！

**Comment by Jerryyuanyuan** [comment]
> 同样的问题

用pc浏览器，搜一搜，搜到对应视频后有不加密的视频，亲测有效！

**Comment by lap888** [comment]
看这个视频，下载方式便捷，有需要的联系微信 wkc19891
[直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)

**Comment by lap888** [comment]
> 看这个视频，下载方式便捷，有需要的联系微信 wkc19891 [直接看操作 简单快捷](http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eez3Y79SxtvVL0L7CkPM6dFibFeI6caGYwFFfHtkRNfURfTQEbib3u45kRn0uz0OMuCeH0nfSM4KdKEI0MXvfG68Rztuib1KHFmxAYX1YBPicWkOkYHK6icBDRde9f8ojmnDRksWVSicPw56hXUw&token=xNChlCtdOp4qNHlrrZhYpwwIrKfYS7Egzz3jZWeFqLVosIjlAafU5yEcgSkluwC9294kSgRDIShrZClJKHFpyg9XMU4NibvyMIxxevIdUfA8yp0HjVLOQ6g&idx=1&a=1&bizid=1023&dotrans=0&hy=SH&m=b6770f4c882d1d04648982a2be108fbb)

http://wxapp.tc.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQBuPPjGAhn5XULO9MXv3LkD4ONUsqVqjicnxQgXXsV7nCPVWvaicnUYX3Rpiaxky7FuI1xGPRicSIj6v54DFXzV8Dup&token=Cvvj5Ix3eez1HP7JibvohWUM3xWundFzwB9CicAUwwhY4sWm7S4XzreTDibdr4iavafxlV7UGxLDSGp2UibOpXXngoW4jvrciaoicVhdicgBrVEvvsbxQrdpPLvXjWc4ZjTk8haic&idx=1&bizid=1023&dotrans=0&hy=SH&m=

**Comment by 666wwx** [comment]
确实在PC搜一搜   搜索“同名视频” 就没有加密了

**Comment by wangguotao1215** [comment]
pc试了试还是不大行

**Comment by danggerenba** [comment]
这个方法可行 问题是我要抓的视频 它没有名字。。。这就很离谱

**Comment by Toweo** [comment]
2023年6月18日测试  
1、下载的视频无法播放
2、预览界面的视频也无法加载出来
<img width="509" alt="微信截图_20230618122012" src="https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/3ae71307-3138-4cc0-81d8-4eb5af30aefd">
<img width="618" alt="微信截图_20230618122027" src="https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/c6896d85-c50d-4c80-b99c-ed5386aacf54">

**Comment by Jerryyuanyuan** [comment]
> 2023年6月18日测试 1、下载的视频无法播放 2、预览界面的视频也无法加载出来 <img alt="微信截图_20230618122012" width="509" src="https://user-images.githubusercontent.com/136948646/246643561-3ae71307-3138-4cc0-81d8-4eb5af30aefd.png">

在PC端 浏览器 “搜一搜” 搜索“同名视频” ，然后用软件抓包下载的就没有加密了

**Comment by Jerryyuanyuan** [comment]
想办法啊想什么？微信的公众号对google和baidu是禁止爬取的，你用常规搜索引擎找不到很正常啊，万一碰运气用sogou找到了，那不是也省事了么？
至于你说的 sogou也搜不到的情况，你可以参考这个换token的方法看下。
https://github.com/lecepin/WeChatVideoDownloader/issues/41#issuecomment-1635227205




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lecepin/WeChatVideoDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lecepin/WeChatVideoDownloader] 2023-6-7测试  视频号把视频已完全加密，下载下来也无法播放 (Issue #38)





 
要是能在别处搜到的话，我为啥要在视频号下载，想啥呢？
