### ISSUE TITLE
2023-06-18测试结果：下载的视频无法播放，预览界面视频无法加载出来

### ISSUE THREAD

**Issue by Toweo** [lecepin/WeChatVideoDownloader#41]
2023-06-18测试结果：下载的视频无法播放，预览界面视频无法加载出来
<img width="509" alt="微信截图_20230618122012" src="https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/e4ed256a-f68f-4bcc-8bbb-dd7adedc35e3">
<img width="600" alt="微信截图_20230618122700" src="https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/0dcdf247-ed67-48d2-baa5-73bb9e6e3abc">

**Comment by daytime001** [comment]
我也是这样，求解决

**Comment by Jerryyuanyuan** [comment]
在PC端 浏览器 “搜一搜” 搜索“同名视频” ，然后再用软件抓包下载的视频就可以正常播放了

**Comment by jiaoyunchao** [comment]
一样的问题，有解决吗？

**Comment by daytime001** [comment]
没有啊


从 Windows 版邮件发送

发件人: jiaoyunchao
发送时间: 2023年6月19日 11:07
收件人: lecepin/WeChatVideoDownloader
抄送: 白昼; Comment
主题: Re: [lecepin/WeChatVideoDownloader]=?UTF-8?Q?_2023-06-18=E6=B5=8B=E8=AF=95=E7=BB=93=E6=9E=9C=EF=BC=9A=E4=B8=8B=E8=BD=BD=E7=9A=84=E8=A7=86=E9=A2=91=E6=97=A0=E6=B3=95=E6=92=AD=E6=94=BE=EF=BC=8C=E9=A2=84=E8=A7=88=E7=95=8C=E9=9D=A2=E8=A7=86=E9=A2=91=E6=97=A0=E6=B3=95=E5=8A=A0=E8=BD=BD=E5=87=BA=E6=9D=A5?==?UTF-8?Q?_=28Issue_#41=29?=

一样的问题，有解决吗？

**Comment by Jerryyuanyuan** [comment]
> 我也是这样，求解决

在PC端 浏览器 搜狗 搜索“同名视频” ，然后再用软件抓包下载的视频就可以正常播放了
![fc03e5bf84d9f981fec8effa9c8b1df](https://github.com/lecepin/WeChatVideoDownloader/assets/18299433/31fa7c76-890b-4f65-9014-71e806dbf94f)
1、视频号找到视频名字
![image](https://github.com/lecepin/WeChatVideoDownloader/assets/18299433/e412519e-e61f-4a95-bd9a-869daf0d9402)
2、搜狗搜索视频，最好找微信标签
![4f0cb23202c1c5ce6fe49890cb4c017](https://github.com/lecepin/WeChatVideoDownloader/assets/18299433/322c66c5-a29e-4ed1-9d86-208f55a280bf)
![d9e45248271dbd66345b71e07c99432](https://github.com/lecepin/WeChatVideoDownloader/assets/18299433/d6a751e9-b292-467b-be7e-6f76d762a785)
![951821e9b35bf9ce8c02167266c3323](https://github.com/lecepin/WeChatVideoDownloader/assets/18299433/3b773496-22d9-4047-a713-c3a613f46d52)
3、播放再到，工具的抓包记录看，不就有了么，点击预览不就OK了么？

非得喂到嘴里才吃。。。。

**Comment by daytime001** [comment]
你这个方法只适用于微信视频号作者在别的平台上也发了视频能被浏览器搜到，并且名字一样，既然能搜到我干嘛还要用这个软件呢，直接随便一个抓包软件不就可以下了嘛，不就是想直接在微信视频号上下载才用它的嘛
真的搞笑。。。。。。。

从 Windows 版邮件发送

发件人: Jerryyuanyuan
发送时间: 2023年6月19日 12:03
收件人: lecepin/WeChatVideoDownloader
抄送: 白昼; Comment
主题: Re: [lecepin/WeChatVideoDownloader]=?UTF-8?Q?_2023-06-18=E6=B5=8B=E8=AF=95=E7=BB=93=E6=9E=9C=EF=BC=9A=E4=B8=8B=E8=BD=BD=E7=9A=84=E8=A7=86=E9=A2=91=E6=97=A0=E6=B3=95=E6=92=AD=E6=94=BE=EF=BC=8C=E9=A2=84=E8=A7=88=E7=95=8C=E9=9D=A2=E8=A7=86=E9=A2=91=E6=97=A0=E6=B3=95=E5=8A=A0=E8=BD=BD=E5=87=BA=E6=9D=A5?==?UTF-8?Q?_=28Issue_#41=29?=

我也是这样，求解决
在PC端 浏览器 搜狗 搜索“同名视频” ，然后再用软件抓包下载的视频就可以正常播放了

1、视频号找到视频名字

2、搜狗搜索视频，最好找微信标签



3、播放再到，工具的抓包记录看，不就有了么，点击预览不就OK了么？
非得喂到嘴里才吃。。。。

**Comment by Jerryyuanyuan** [comment]
> 
那应该去找牛逼plus的视频解码软件，而不是抓包软件。
因为这本身已经不是抓包软件的功能了。

我vlc也试过了不行，或许ffmpeg可以，也或者opencv或者moviepy加载进来会有惊喜？我是懒得折腾了，本身我自己的想法就是取巧，找一下有没有可替代的不加密的原版视频存在。如果只是想播放视频号下载到的原始文件，那么你只能搞视频解码了。

**Comment by daytime001** [comment]
实在不行还是录屏吧哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月19日(周一) 中午1:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lecepin/WeChatVideoDownloader] 2023-06-18测试结果：下载的视频无法播放，预览界面视频无法加载出来 (Issue #41)




   
那应该去找牛逼plus的视频解码软件，而不是抓包软件。
 因为这本身已经不是抓包软件的功能了。
 
我vlc也试过了不行，或许ffmpeg可以，也或者opencv或者moviepy加载进来会有惊喜？我是懒得折腾了，本身我自己的想法就是取巧，找一下有没有可替代的不加密的原版视频存在。如果只是想播放视频号下载到的原始文件，那么你只能搞视频解码了。

**Comment by Jerryyuanyuan** [comment]
> 实在不行还是录屏吧哈哈哈
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月19日(周一) 中午1:34 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lecepin/WeChatVideoDownloader] 2023-06-18测试结果：下载的视频无法播放，预览界面视频无法加载出来 (Issue #41) 那应该去找牛逼plus的视频解码软件，而不是抓包软件。 因为这本身已经不是抓包软件的功能了。 我vlc也试过了不行，或许ffmpeg可以，也或者opencv或者moviepy加载进来会有惊喜？我是懒得折腾了，本身我自己的想法就是取巧，找一下有没有可替代的不加密的原版视频存在。如果只是想播放视频号下载到的原始文件，那么你只能搞视频解码了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

死马当活马医！

**Comment by yadjxx** [comment]
也是一样的结果，请大神更新一下吧！

**Comment by viviman1314** [comment]
大神们，为何我Mac不能下载安装呢？求指点

**Comment by 2085886325** [comment]
https://findermp.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQBbkHyZZxfw0aYsDoUTnTUBXRgJKVkXdia04o8VvyfUJbN57Hz83EuvgKeclb5mwZESb3qtXic9cO6838tpZbndNb&bizid=1023&dotrans=0&hy=SH&idx=1&m=&partscene=4&X-snsvideoflag=W30&token=换成你成功的token


前面的url以及参数都换成你不能预览的那个视频url，对比我发的这个，其余多的参数删除掉，后面的token你随便在搜一搜搜个东西就会抓出来一个可以预览的视频，把那个可以预览视频url里面的token换到你的这里面来，也就是我发的url的末尾，这样就能出来了
![image](https://github.com/lecepin/WeChatVideoDownloader/assets/61336743/3b960dd6-41a1-4e7d-9744-a2aeae953c5b)

亲测可以


前面的url以及参数都换成你不能预览的那个视频url，对比我发的这个，其余多的参数删除掉，后面的token你随便在搜一搜搜个东西就会抓出来一个可以预览的视频，把那个可以预览视频url里面的token换到你的这里面来，也就是我发的url的末尾，这样就能出来了
亲测可以
