### ISSUE TITLE
希望能讲讲功能实现的流程原理

### ISSUE THREAD

**Issue by zhangya4548** [lecepin/WeChatVideoDownloader#5]
大佬能讲讲功能实现的流程原理吗?
小弟会别的语言想练练手自己实现一个

**Comment by lecepin** [comment]
- 创建一个https服务器
- 设置系统代理服务器为上面创建的这个
- 通过授信证书，可以实现https明文查看
- 判断是否为视频请求

**Comment by lecepin** [comment]
手机同样需要安装证书才可以，否则是无法明文https的。

手机不同系统，不同型号，对证书的安装方式不同，建议直接在 pc 中操作。

**Comment by zhangya4548** [comment]
但是我抓包手机怎么抓包不到微信上的请求呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 乐平 ***@***.***&gt;
发送时间: 2022年6月8日 22:54
收件人: lecepin/WeChatVideoDownloader ***@***.***&gt;
抄送: zhangya4548 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lecepin/WeChatVideoDownloader] 希望能讲讲功能实现的流程原理 (Issue #5)





  
创建一个https服务器 

设置系统代理服务器为上面创建的这个 

通过授信证书，可以实现https明文查看 

判断是否为视频请求
