### ISSUE TITLE
【教程】解决下载后不能播放的问题，改一个数字就行

### ISSUE THREAD

**Issue by Toweo** [lecepin/WeChatVideoDownloader#50]
这里有一个网友重新写的软件
https://github.com/putyy/res-downloader
我测试了可以用

如果不想换软件的可以尝试用下面的教程
教程来源，某宝付费买的，附带的教程
1、打开软件，播放您需要下载的视频号视频
![1001](https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/16fe5783-43d0-4c08-a962-2b055dcd89d6)

2、获取到对应的链接后，3击鼠标左键，选中对应的连接，CTRL+C复制下来

3、然后将链接开头的 **20302** 改为 **20304**，数字的位置就在域名后的第二个斜杠位置
![1002](https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/f889a68e-f548-40e9-a514-4b5245d4af55)

4、将该链接粘贴至浏览器中，然后在浏览器中右键，另存为，重命名“文件名.MP4”,保存即可
这个时候就下载完成了
![1003](https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/18dd1ef4-f902-4747-8126-79283cb0413d)
![1004](https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/7da3fa4e-b98b-497a-b5bb-c2e01ef79a36)

以上下载的是普通清晰度的画质，如果你需要超高清原版视频，可以进一步修改链接，删掉以下这些参数：&a=、&idx=、&extg=、&svrbypass=、&svrnonce=、&fexam=，简单来说就是只留 encfilekey 和 token 部分的字符串

然后将修改好后的链接按照上一个下载步骤操作即可
![1006](https://github.com/lecepin/WeChatVideoDownloader/assets/136948646/c518c729-9c06-4b84-84f0-849b6cfedd48)

**Comment by joker1396** [comment]
确实失效了
