### ISSUE TITLE
mac的下载了表示文件已损毁,打不开的

### ISSUE THREAD

**Issue by pengzhiqiang110** [lecepin/WeChatVideoDownloader#52]

**Comment by wenhairu** [comment]
开发者好像不看issues

**Comment by lecepin** [comment]
<img width="540" alt="image" src="https://github.com/lecepin/WeChatVideoDownloader/assets/11046969/5fead299-3fb0-4ee4-80ee-9af40f559098">
<img width="280" alt="image" src="https://github.com/lecepin/WeChatVideoDownloader/assets/11046969/e98e4126-651e-4445-9d0d-083976351cb5">

我这边正常，截图下你的错误信息及系统信息。

**Comment by LonelyPlanet199** [comment]
1.0版本下载以后打不开，文件损坏，而且每次下载，文件大小都不一样。

**Comment by LonelyPlanet199** [comment]
> 1.0版本下载以后打不开，文件损坏，而且每次下载，文件大小都不一样。

我是说软件可以下载安装，并且初始化，但下载的视频打不开。另外有没有给Intel芯片的Mac版本？

**Comment by lecepin** [comment]
> 1.0版本下载以后打不开，文件损坏，而且每次下载，文件大小都不一样。

1.0.0已失效，请下载最新版本

**Comment by ohyeswind** [comment]
intel版MAC什么时候能支持呢？

**Comment by LonelyPlanet199** [comment]
intel版MAC什么时候能支持呢？

乐平 ***@***.***> 于2023年9月5日周二 18:33写道：

**Comment by lynhao** [comment]
<img width="368" alt="截屏2023-09-07 下午6 42 34" src="https://github.com/lecepin/WeChatVideoDownloader/assets/14127727/fd91397a-0683-4fde-bfb0-a39d00b36265">
<img width="514" alt="截屏2023-09-07 下午6 42 48" src="https://github.com/lecepin/WeChatVideoDownloader/assets/14127727/2b719cd0-ef17-414d-84c1-8d2cc107919f">
@lecepin 平总，我安装过程也出现这个问题

**Comment by lecepin** [comment]
下载下新的，再试下

**Comment by lynhao** [comment]
> 下载下新的，再试下

<img width="740" alt="截屏2023-09-07 下午9 19 46" src="https://github.com/lecepin/WeChatVideoDownloader/assets/14127727/d70d561e-5b1c-4757-8ff6-47ef171d9813">
错误提示变了，打开了安全面板，没跟一些软件一样提示继续安装

**Comment by lynhao** [comment]
@lecepin 正常安装了，感谢平总🌹
