### ISSUE TITLE
捕捉不到视频

### ISSUE THREAD

**Issue by lynhao** [lecepin/WeChatVideoDownloader#53]
<img width="1448" alt="截屏2023-09-07 下午9 45 04" src="https://github.com/lecepin/WeChatVideoDownloader/assets/14127727/6d17062b-06a2-4090-be50-84c713992810">

@lecepin 平总，似乎没有捕抓到呀？求指教

**Comment by AllahGold** [comment]
我一开始也是捕捉不了，后来想可能是因为开了其他代理，就重启了下电脑，管理员模式打开这个软件，然后再开微信，就好了。

**Comment by 9964858** [comment]
似乎是微信内置的浏览器没有走代理
