### ISSUE TITLE
安装打开即报错

### ISSUE THREAD

**Issue by csercser** [lecepin/WeChatVideoDownloader#58]
大佬好，我是win7,  64位，顺利安装1.0.1版本，但是打开就报错：无法定位程序输入点 DiscardVirtualMemory 于动态链接库KERNEL32.dll上。 
![1695265274766](https://github.com/lecepin/WeChatVideoDownloader/assets/145632858/2fe0089e-e308-48c1-84e1-8920892d748b)

**Comment by lecepin** [comment]
https://learn.microsoft.com/zh-cn/windows/win32/api/memoryapi/nf-memoryapi-discardvirtualmemory
<img width="816" alt="image" src="https://github.com/lecepin/WeChatVideoDownloader/assets/11046969/b5dfee9d-3a12-4c28-96e1-1ece1842786b">

**Comment by gfanslee** [comment]
同问，是软件不再支持win7了吗

**Comment by lecepin** [comment]
> https://learn.microsoft.com/zh-cn/windows/win32/api/memoryapi/nf-memoryapi-discardvirtualmemory <img alt="image" width="816" src="https://user-images.githubusercontent.com/11046969/270851123-b5dfee9d-3a12-4c28-96e1-1ece1842786b.png">
