### ISSUE TITLE
mac 版本v1.0.1 捕捉到的视频无法预览，下载后无法打开

### ISSUE THREAD

**Issue by meetlany** [lecepin/WeChatVideoDownloader#60]
创作者您好，感谢辛苦维护软件，第一次使用，版本为v1.0.1，设备Mac，初始化成功，可以捕捉到链接，但是捕捉后无法预览，下载后无法打开，复制捕捉到的链接使用其它方式下载后，依旧无法打开。

**Comment by Elegantment** [comment]
跟他这边关系应该不大，估计是腾讯那边做的手脚，把链接获取后用其他下载软件下载也是无法播放，可能给加密了

**Comment by walker88866** [comment]
刚下载好，看样子不用试了。找到替代工具了吗，不知道淘宝卖的视频号下载工具，能不能下载？

**Comment by walker88866** [comment]
下载安装后，碰上了同样的问题。下载的视频无法播放

**Comment by leekoko** [comment]
朋友们，是否有替代方案
