### ISSUE TITLE
好像用不了了？

### ISSUE THREAD

**Issue by cxq1** [lecepin/WeChatVideoDownloader#61]
好像用不了了？

**Comment by cnslzr** [comment]
可以下载，但是预览失败，下载的文件也打不开。

**Comment by cxq1** [comment]
> 可以下载，但是预览失败，下载的文件也打不开。

还是用不了

**Comment by goldoctor** [comment]
解析地址 20303 换成 20304 也没办法，下载的mp4无法打开，那帮企鹅又开会了。。。。

**Comment by jetmanyan** [comment]
怎么办啊，用不了。着急。
抖音目前还好用。

**Comment by tianyaomoxing** [comment]
我可以测试下你们无法下载的地址，目前我这边下载正常，打开也正常，但是我不确定是否和我这边环境有关系。。。
10月1日朋友找我帮下载，下载后确实打不开，后来又试了下可以了，刚刚测试了下还是可以的
但是我不确定我的是不是个例，

我这边环境：
Macos 10.14.5 
微信版本：3.5.5（23551）

**Comment by nixingshiguang** [comment]
> 解析地址 20303 换成 20304 也没办法，下载的mp4无法打开，那帮企鹅又开会了。。。。

应该开完会了，界面变了，我的也用不了了，win11

**Comment by lecepin** [comment]
#66
