### ISSUE TITLE
启动失败——无法找到入口

### ISSUE THREAD

**Issue by kdilese** [lecepin/WeChatVideoDownloader#69]
无法定位程序输入点DiscardVirtualMemory于动态链接库KERNEL32.dll上，系统是win7 x64，用系统管理员权限启动，请问这要怎么解决？

**Comment by lecepin** [comment]
![image](https://github.com/lecepin/WeChatVideoDownloader/assets/11046969/0ad22945-3fe6-4525-9902-0e19179b4cb1)
