### ISSUE TITLE
怎么重装软件证书啊

### ISSUE THREAD

**Issue by xxr121** [lecepin/WeChatVideoDownloader#71]
我原来删掉了软件的证书，现在重新安装软件不能初始化了。要怎么样才能重新初始化，或者直接安装证书

**Comment by daidaiworm** [comment]
是下载的视频不能播放了，想要重置吗？我前几天可以，今天不行了。

**Comment by shabiaizai** [comment]
我也是手贱删除了证书，重装也是无法初始化

**Comment by xxr121** [comment]
> 我也是手贱删除了证书，重装也是无法初始化

后面我在一个新的用户上面重装了这个软件，就可以用了

**Comment by xxr121** [comment]
> 是下载的视频不能播放了，想要重置吗？我前几天可以，今天不行了。
是这样的，后面我想重装软件，再初始化，看看能不能用，结果删掉证书之后重装软件不能初始化了

**Comment by shabiaizai** [comment]
> > 我也是手贱删除了证书，重装也无法初始化
> 
> 后面我在一个新用户上面重装了这个软件，就可以用了

只有一个用户哈哈，创多一个会显得乱，谢谢思路，改天试试

**Comment by lecepin** [comment]
#45
