### ISSUE TITLE
在win7系统下 运行不了，出现无法定位程序输入点DiscardVirtualMemory

### ISSUE THREAD

**Issue by zhouhounan** [lecepin/WeChatVideoDownloader#72]
<img width="324" alt="image" src="https://github.com/lecepin/WeChatVideoDownloader/assets/17348292/27d86ebb-3c18-4997-bfc2-6634a434b01e">

**Comment by lecepin** [comment]
![image](https://github.com/lecepin/WeChatVideoDownloader/assets/11046969/f8703f36-a2f6-4309-bc1b-372eb4692ed4)
