### ISSUE TITLE
Can not play the downloaded video.无法播放下载的视频，疑似已加密

### ISSUE THREAD

**Issue by aowd** [lecepin/WeChatVideoDownloader#74]
软件可以正常嗅探并下载到播放的视频，但视频无法用potplayer等视频播放软件播放，用Die检测文件发现检测不出文件头，疑似腾讯已对视频进行加密处理。希望有大神能够解除加密！
this soft can sniffer and download the video,but the video cannot play by potplayer. when using die to detect the video file header,but find none.guese the tencent has encrypt the video file .

**Comment by dyf502** [comment]
是的，同样遇到问题，不行了

**Comment by LincolnBurrows** [comment]
+1 铁铁

**Comment by LincolnBurrows** [comment]
先去搜一搜界面下载视频， 可以预览， 可以下载， 下载后可正常播放！

**Comment by hcycc** [comment]
确实下载后不能播放
